module.exports = {
  SHOW_ADD_POPUP: 'SHOW_ADD_POPUP',
  HIDE_ADD_POPUP: 'HIDE_ADD_POPUP',
  SHOW_EDIT_POPUP: 'SHOW_EDIT_POPUP',
  HIDE_EDIT_POPUP: 'HIDE_EDIT_POPUP',
  SHOW_DIALOG: 'SHOW_DIALOG',
  HIDE_DIALOG: 'HIDE_DIALOG',
};
